version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes: 
      - './data:/data/db'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zagetreviews
      - MONGO_INITDB_ROOT_PASSWORD=zagetreviews
      - MONGO_INITDB_DATABASE=apateez-reviews
    command: mongod --auth
    